version: "3.9"
services:
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      DB_URL: "mongodb://db/learning-docker"
    volumes:
      - ./:/app
  db:
    image: mongo:6.0.4
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
